(define (domain star-domain-try3)
  (:requirements :equality)
  (:predicates (disk ?x) (smaller ?x ?y) (on ?x ?y) (clear ?x))
  
  (:action move-disk-center
           :parameters (?disk ?below-disk)
           :precondition (and (disk ?disk)
                              (smaller ?disk p0)
                              (not (= p0 ?below-disk))
                              (not (= p0 ?disk))
                              (not (= ?below-disk ?disk))
                              (on ?disk ?below-disk)
                              (clear ?disk)
                              (clear p0))
                              
           :effect (and (clear ?below-disk)
                        (on ?disk p0)
                        (not (on ?disk ?below-disk))
                        (not (clear p0)) ) )
                        
  (:action move-disk-peg
           :parameters (?disk ?new-below-disk)
           :precondition (and (disk ?disk)
                              (smaller ?disk ?new-below-disk)
                              (not (= ?new-below-disk p0))
                              (not (= ?new-below-disk ?disk))
                              (not (= p0 ?disk))
                              (on ?disk p0)
                              (clear ?disk)
                              (clear ?new-below-disk))
                              
           :effect (and (clear p0)
                        (on ?disk ?new-below-disk)
                        (not (on ?disk p0))
                        (not (clear ?new-below-disk)) ) )
)